name:                funEvalExpr
version:             1
github:              "skyf0l/funEvalExpr"
license:             BSD3
author:              "Skyf0l"
maintainer:          "tom.rorato@epitech.eu"
copyright:           "2021 Skyf0l"

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/funEvalExpr#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  funEvalExpr:
    main:                MainEvalExpr.hs
    source-dirs:         app
    ghc-options:
    - -main-is MainEvalExpr
    dependencies:
    - funEvalExpr

  funInfixToPostfixExpr:
    main:                MainInfixToPostfixExpr.hs
    source-dirs:         app/sub_apps
    ghc-options:
    - -main-is MainInfixToPostfixExpr
    dependencies:
    - funEvalExpr

  funEvalPostfixExpr:
    main:                MainEvalPostfixExpr.hs
    source-dirs:         app/sub_apps
    ghc-options:
    - -main-is MainEvalPostfixExpr
    dependencies:
    - funEvalExpr
